import { FSMMetadata, FSMStep } from './supabase';

export const mockFSM: FSMMetadata = {
	id: 'mock-fsm-1',
	title: 'Sample Adventure Game',
	description: 'A simple text adventure game demonstrating FSM capabilities',
	user_id: 'demo-user',
	num_steps: 4,
	created_at: new Date().toISOString(),
	updated_at: new Date().toISOString(),
};

export const mockSteps: FSMStep[] = [
	{
		id: 'start',
		fsm_id: mockFSM.id,
		title: 'Start',
		content: 'You find yourself in a mysterious room. There are two doors: one red and one blue.',
		media_type: 'text',
		next_steps: ['red-door', 'blue-door'],
		position_x: 250,
		position_y: 100,
		created_at: new Date().toISOString(),
		updated_at: new Date().toISOString(),
	},
	{
		id: 'red-door',
		fsm_id: mockFSM.id,
		title: 'Red Door',
		content: 'Behind the red door is a treasure chest!',
		media_type: 'image',
		media_url: 'https://picsum.photos/200/300',
		next_steps: ['treasure'],
		position_x: 100,
		position_y: 250,
		created_at: new Date().toISOString(),
		updated_at: new Date().toISOString(),
	},
	{
		id: 'blue-door',
		fsm_id: mockFSM.id,
		title: 'Blue Door',
		content: 'The blue door leads to a magical portal!',
		media_type: 'video',
		media_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
		next_steps: ['portal'],
		position_x: 400,
		position_y: 250,
		created_at: new Date().toISOString(),
		updated_at: new Date().toISOString(),
	},
	{
		id: 'treasure',
		fsm_id: mockFSM.id,
		title: 'Treasure',
		content: 'You found a chest full of gold! Game Over.',
		media_type: 'text',
		next_steps: [],
		position_x: 100,
		position_y: 400,
		created_at: new Date().toISOString(),
		updated_at: new Date().toISOString(),
	},
	{
		id: 'portal',
		fsm_id: mockFSM.id,
		title: 'Portal',
		content: 'The portal transports you to another dimension! Game Over.',
		media_type: 'text',
		next_steps: [],
		position_x: 400,
		position_y: 400,
		created_at: new Date().toISOString(),
		updated_at: new Date().toISOString(),
	},
]; 